/**
 * @file robot.c
 *
 * @brief This source file was generated by cantools version 42.0.1 Wed Aug  5 03:40:02 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "robot.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int robot_velocity_command_pack(
    uint8_t *dst_p,
    const struct robot_velocity_command_t *src_p,
    size_t size)
{
    uint32_t left_vel_setpoint;
    uint32_t right_vel_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&left_vel_setpoint, &src_p->left_vel_setpoint, sizeof(left_vel_setpoint));
    dst_p[0] |= pack_left_shift_u32(left_vel_setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(left_vel_setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(left_vel_setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(left_vel_setpoint, 24u, 0xffu);
    memcpy(&right_vel_setpoint, &src_p->right_vel_setpoint, sizeof(right_vel_setpoint));
    dst_p[4] |= pack_left_shift_u32(right_vel_setpoint, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(right_vel_setpoint, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(right_vel_setpoint, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(right_vel_setpoint, 24u, 0xffu);

    return (8);
}

int robot_velocity_command_unpack(
    struct robot_velocity_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t left_vel_setpoint;
    uint32_t right_vel_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    left_vel_setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    left_vel_setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    left_vel_setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    left_vel_setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->left_vel_setpoint, &left_vel_setpoint, sizeof(dst_p->left_vel_setpoint));
    right_vel_setpoint = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    right_vel_setpoint |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    right_vel_setpoint |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    right_vel_setpoint |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->right_vel_setpoint, &right_vel_setpoint, sizeof(dst_p->right_vel_setpoint));

    return (0);
}

int robot_velocity_command_init(struct robot_velocity_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_velocity_command_t));

    return 0;
}

float robot_velocity_command_left_vel_setpoint_encode(double value)
{
    return (float)(value);
}

double robot_velocity_command_left_vel_setpoint_decode(float value)
{
    return ((double)value);
}

bool robot_velocity_command_left_vel_setpoint_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool robot_velocity_command_left_vel_setpoint_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

float robot_velocity_command_right_vel_setpoint_encode(double value)
{
    return (float)(value);
}

double robot_velocity_command_right_vel_setpoint_decode(float value)
{
    return ((double)value);
}

bool robot_velocity_command_right_vel_setpoint_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool robot_velocity_command_right_vel_setpoint_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int robot_velocity_feedback_pack(
    uint8_t *dst_p,
    const struct robot_velocity_feedback_t *src_p,
    size_t size)
{
    uint32_t left_ticks;
    uint32_t right_ticks;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    left_ticks = (uint32_t)src_p->left_ticks;
    dst_p[0] |= pack_left_shift_u32(left_ticks, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(left_ticks, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(left_ticks, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(left_ticks, 24u, 0xffu);
    right_ticks = (uint32_t)src_p->right_ticks;
    dst_p[4] |= pack_left_shift_u32(right_ticks, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(right_ticks, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(right_ticks, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(right_ticks, 24u, 0xffu);

    return (8);
}

int robot_velocity_feedback_unpack(
    struct robot_velocity_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t left_ticks;
    uint32_t right_ticks;

    if (size < 8u) {
        return (-EINVAL);
    }

    left_ticks = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    left_ticks |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    left_ticks |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    left_ticks |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->left_ticks = (int32_t)left_ticks;
    right_ticks = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    right_ticks |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    right_ticks |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    right_ticks |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->right_ticks = (int32_t)right_ticks;

    return (0);
}

int robot_velocity_feedback_init(struct robot_velocity_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_velocity_feedback_t));

    return 0;
}

int32_t robot_velocity_feedback_left_ticks_encode(double value)
{
    return (int32_t)(value);
}

double robot_velocity_feedback_left_ticks_decode(int32_t value)
{
    return ((double)value);
}

bool robot_velocity_feedback_left_ticks_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool robot_velocity_feedback_left_ticks_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int32_t robot_velocity_feedback_right_ticks_encode(double value)
{
    return (int32_t)(value);
}

double robot_velocity_feedback_right_ticks_decode(int32_t value)
{
    return ((double)value);
}

bool robot_velocity_feedback_right_ticks_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool robot_velocity_feedback_right_ticks_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int robot_steering_command_pack(
    uint8_t *dst_p,
    const struct robot_steering_command_t *src_p,
    size_t size)
{
    uint32_t steering_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&steering_setpoint, &src_p->steering_setpoint, sizeof(steering_setpoint));
    dst_p[0] |= pack_left_shift_u32(steering_setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(steering_setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(steering_setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(steering_setpoint, 24u, 0xffu);

    return (8);
}

int robot_steering_command_unpack(
    struct robot_steering_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t steering_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    steering_setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    steering_setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    steering_setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    steering_setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->steering_setpoint, &steering_setpoint, sizeof(dst_p->steering_setpoint));

    return (0);
}

int robot_steering_command_init(struct robot_steering_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_steering_command_t));

    return 0;
}

float robot_steering_command_steering_setpoint_encode(double value)
{
    return (float)(value);
}

double robot_steering_command_steering_setpoint_decode(float value)
{
    return ((double)value);
}

bool robot_steering_command_steering_setpoint_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool robot_steering_command_steering_setpoint_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int robot_steering_feedback_pack(
    uint8_t *dst_p,
    const struct robot_steering_feedback_t *src_p,
    size_t size)
{
    uint32_t steering_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&steering_angle, &src_p->steering_angle, sizeof(steering_angle));
    dst_p[0] |= pack_left_shift_u32(steering_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(steering_angle, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(steering_angle, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(steering_angle, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->at_target, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->pot_fault, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->out_of_range, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->saturated, 3u, 0x08u);

    return (8);
}

int robot_steering_feedback_unpack(
    struct robot_steering_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t steering_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    steering_angle = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    steering_angle |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    steering_angle |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    steering_angle |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->steering_angle, &steering_angle, sizeof(dst_p->steering_angle));
    dst_p->at_target = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->pot_fault = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->out_of_range = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->saturated = unpack_right_shift_u8(src_p[4], 3u, 0x08u);

    return (0);
}

int robot_steering_feedback_init(struct robot_steering_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_steering_feedback_t));

    return 0;
}

float robot_steering_feedback_steering_angle_encode(double value)
{
    return (float)(value);
}

double robot_steering_feedback_steering_angle_decode(float value)
{
    return ((double)value);
}

bool robot_steering_feedback_steering_angle_is_in_range(float value)
{
    (void)value;

    return (true);
}

bool robot_steering_feedback_steering_angle_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t robot_steering_feedback_at_target_encode(double value)
{
    return (uint8_t)(value);
}

double robot_steering_feedback_at_target_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_steering_feedback_at_target_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool robot_steering_feedback_at_target_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t robot_steering_feedback_pot_fault_encode(double value)
{
    return (uint8_t)(value);
}

double robot_steering_feedback_pot_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_steering_feedback_pot_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool robot_steering_feedback_pot_fault_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t robot_steering_feedback_out_of_range_encode(double value)
{
    return (uint8_t)(value);
}

double robot_steering_feedback_out_of_range_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_steering_feedback_out_of_range_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool robot_steering_feedback_out_of_range_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t robot_steering_feedback_saturated_encode(double value)
{
    return (uint8_t)(value);
}

double robot_steering_feedback_saturated_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_steering_feedback_saturated_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool robot_steering_feedback_saturated_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int robot_reset_command_pack(
    uint8_t *dst_p,
    const struct robot_reset_command_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->reset, 0u, 0xffu);

    return (1);
}

int robot_reset_command_unpack(
    struct robot_reset_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->reset = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int robot_reset_command_init(struct robot_reset_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_reset_command_t));

    return 0;
}

uint8_t robot_reset_command_reset_encode(double value)
{
    return (uint8_t)(value);
}

double robot_reset_command_reset_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_reset_command_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool robot_reset_command_reset_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int robot_imu_accel_pack(
    uint8_t *dst_p,
    const struct robot_imu_accel_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->sequence, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved, 0u, 0xffu);

    return (8);
}

int robot_imu_accel_unpack(
    struct robot_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    dst_p->sequence = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int robot_imu_accel_init(struct robot_imu_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_imu_accel_t));

    return 0;
}

int16_t robot_imu_accel_accel_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double robot_imu_accel_accel_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool robot_imu_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_accel_accel_x_is_in_phys_range(double value)
{
    return ((value >= -32.768) && (value <= 32.767));
}

int16_t robot_imu_accel_accel_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double robot_imu_accel_accel_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool robot_imu_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_accel_accel_y_is_in_phys_range(double value)
{
    return ((value >= -32.768) && (value <= 32.767));
}

int16_t robot_imu_accel_accel_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double robot_imu_accel_accel_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool robot_imu_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_accel_accel_z_is_in_phys_range(double value)
{
    return ((value >= -32.768) && (value <= 32.767));
}

uint8_t robot_imu_accel_sequence_encode(double value)
{
    return (uint8_t)(value);
}

double robot_imu_accel_sequence_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_imu_accel_sequence_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_accel_sequence_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t robot_imu_accel_reserved_encode(double value)
{
    return (uint8_t)(value);
}

double robot_imu_accel_reserved_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_imu_accel_reserved_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_accel_reserved_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int robot_imu_gyro_flags_pack(
    uint8_t *dst_p,
    const struct robot_imu_gyro_flags_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[2] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[4] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->imu_reset, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->sequence, 0u, 0xffu);

    return (8);
}

int robot_imu_gyro_flags_unpack(
    struct robot_imu_gyro_flags_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;
    dst_p->imu_reset = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->sequence = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int robot_imu_gyro_flags_init(struct robot_imu_gyro_flags_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_imu_gyro_flags_t));

    return 0;
}

int16_t robot_imu_gyro_flags_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double robot_imu_gyro_flags_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool robot_imu_gyro_flags_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_gyro_flags_gyro_x_is_in_phys_range(double value)
{
    return ((value >= -32.768) && (value <= 32.767));
}

int16_t robot_imu_gyro_flags_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double robot_imu_gyro_flags_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool robot_imu_gyro_flags_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_gyro_flags_gyro_y_is_in_phys_range(double value)
{
    return ((value >= -32.768) && (value <= 32.767));
}

int16_t robot_imu_gyro_flags_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double robot_imu_gyro_flags_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool robot_imu_gyro_flags_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_gyro_flags_gyro_z_is_in_phys_range(double value)
{
    return ((value >= -32.768) && (value <= 32.767));
}

uint8_t robot_imu_gyro_flags_imu_reset_encode(double value)
{
    return (uint8_t)(value);
}

double robot_imu_gyro_flags_imu_reset_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_imu_gyro_flags_imu_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool robot_imu_gyro_flags_imu_reset_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t robot_imu_gyro_flags_sequence_encode(double value)
{
    return (uint8_t)(value);
}

double robot_imu_gyro_flags_sequence_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_imu_gyro_flags_sequence_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_imu_gyro_flags_sequence_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int robot_vehicle_status_pack(
    uint8_t *dst_p,
    const struct robot_vehicle_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->speed, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->gear, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->trip_m, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->trip_m, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(src_p->odo_m, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->odo_m, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->odo_m, 16u, 0xffu);

    return (8);
}

int robot_vehicle_status_unpack(
    struct robot_vehicle_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->speed = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->speed |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gear = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->trip_m = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->trip_m |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->odo_m = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    dst_p->odo_m |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    dst_p->odo_m |= unpack_left_shift_u32(src_p[7], 16u, 0xffu);

    return (0);
}

int robot_vehicle_status_init(struct robot_vehicle_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_vehicle_status_t));

    return 0;
}

uint16_t robot_vehicle_status_speed_encode(double value)
{
    return (uint16_t)(value);
}

double robot_vehicle_status_speed_decode(uint16_t value)
{
    return ((double)value);
}

bool robot_vehicle_status_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool robot_vehicle_status_speed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint8_t robot_vehicle_status_gear_encode(double value)
{
    return (uint8_t)(value);
}

double robot_vehicle_status_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_vehicle_status_gear_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool robot_vehicle_status_gear_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 2.0));
}

uint16_t robot_vehicle_status_trip_m_encode(double value)
{
    return (uint16_t)(value);
}

double robot_vehicle_status_trip_m_decode(uint16_t value)
{
    return ((double)value);
}

bool robot_vehicle_status_trip_m_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool robot_vehicle_status_trip_m_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint32_t robot_vehicle_status_odo_m_encode(double value)
{
    return (uint32_t)(value);
}

double robot_vehicle_status_odo_m_decode(uint32_t value)
{
    return ((double)value);
}

bool robot_vehicle_status_odo_m_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool robot_vehicle_status_odo_m_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 16777215.0));
}

int robot_battery_status_pack(
    uint8_t *dst_p,
    const struct robot_battery_status_t *src_p,
    size_t size)
{
    uint16_t current;
    uint16_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->voltage, 0u, 0xffu);
    current = (uint16_t)src_p->current;
    dst_p[1] |= pack_left_shift_u16(current, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->soc, 0u, 0xffu);
    power = (uint16_t)src_p->power;
    dst_p[4] |= pack_left_shift_u16(power, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(power, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->range, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->range, 8u, 0xffu);

    return (8);
}

int robot_battery_status_unpack(
    struct robot_battery_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current;
    uint16_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    current = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    current |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->current = (int16_t)current;
    dst_p->soc = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    power = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    power |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->power = (int16_t)power;
    dst_p->range = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->range |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int robot_battery_status_init(struct robot_battery_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_battery_status_t));

    return 0;
}

uint8_t robot_battery_status_voltage_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double robot_battery_status_voltage_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool robot_battery_status_voltage_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_battery_status_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 25.5));
}

int16_t robot_battery_status_current_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double robot_battery_status_current_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool robot_battery_status_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_battery_status_current_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

uint8_t robot_battery_status_soc_encode(double value)
{
    return (uint8_t)(value);
}

double robot_battery_status_soc_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_battery_status_soc_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool robot_battery_status_soc_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

int16_t robot_battery_status_power_encode(double value)
{
    return (int16_t)(value);
}

double robot_battery_status_power_decode(int16_t value)
{
    return ((double)value);
}

bool robot_battery_status_power_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool robot_battery_status_power_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

uint16_t robot_battery_status_range_encode(double value)
{
    return (uint16_t)(value);
}

double robot_battery_status_range_decode(uint16_t value)
{
    return ((double)value);
}

bool robot_battery_status_range_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool robot_battery_status_range_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

int robot_node_ping_request_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_request_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->seq, 0u, 0xffu);

    return (1);
}

int robot_node_ping_request_unpack(
    struct robot_node_ping_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->seq = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int robot_node_ping_request_init(struct robot_node_ping_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_node_ping_request_t));

    return 0;
}

uint8_t robot_node_ping_request_seq_encode(double value)
{
    return (uint8_t)(value);
}

double robot_node_ping_request_seq_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_node_ping_request_seq_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_node_ping_request_seq_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int robot_node_ping_resp_tiva_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_resp_tiva_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->seq, 0u, 0xffu);

    return (1);
}

int robot_node_ping_resp_tiva_unpack(
    struct robot_node_ping_resp_tiva_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->seq = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int robot_node_ping_resp_tiva_init(struct robot_node_ping_resp_tiva_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_node_ping_resp_tiva_t));

    return 0;
}

uint8_t robot_node_ping_resp_tiva_seq_encode(double value)
{
    return (uint8_t)(value);
}

double robot_node_ping_resp_tiva_seq_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_node_ping_resp_tiva_seq_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_node_ping_resp_tiva_seq_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int robot_node_ping_resp_jetson_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_resp_jetson_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->seq, 0u, 0xffu);

    return (1);
}

int robot_node_ping_resp_jetson_unpack(
    struct robot_node_ping_resp_jetson_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->seq = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int robot_node_ping_resp_jetson_init(struct robot_node_ping_resp_jetson_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_node_ping_resp_jetson_t));

    return 0;
}

uint8_t robot_node_ping_resp_jetson_seq_encode(double value)
{
    return (uint8_t)(value);
}

double robot_node_ping_resp_jetson_seq_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_node_ping_resp_jetson_seq_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_node_ping_resp_jetson_seq_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int robot_node_ping_resp_esp32_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_resp_esp32_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->seq, 0u, 0xffu);

    return (1);
}

int robot_node_ping_resp_esp32_unpack(
    struct robot_node_ping_resp_esp32_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->seq = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int robot_node_ping_resp_esp32_init(struct robot_node_ping_resp_esp32_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct robot_node_ping_resp_esp32_t));

    return 0;
}

uint8_t robot_node_ping_resp_esp32_seq_encode(double value)
{
    return (uint8_t)(value);
}

double robot_node_ping_resp_esp32_seq_decode(uint8_t value)
{
    return ((double)value);
}

bool robot_node_ping_resp_esp32_seq_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool robot_node_ping_resp_esp32_seq_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}
