/**
 * @file robot.h
 *
 * @brief This header file was generated by cantools version 42.0.1 Wed Aug  5 03:40:02 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ROBOT_H
#define ROBOT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ROBOT_VELOCITY_COMMAND_FRAME_ID (0x100u)
#define ROBOT_VELOCITY_FEEDBACK_FRAME_ID (0x110u)
#define ROBOT_STEERING_COMMAND_FRAME_ID (0x120u)
#define ROBOT_STEERING_FEEDBACK_FRAME_ID (0x130u)
#define ROBOT_RESET_COMMAND_FRAME_ID (0x140u)
#define ROBOT_IMU_ACCEL_FRAME_ID (0x150u)
#define ROBOT_IMU_GYRO_FLAGS_FRAME_ID (0x160u)
#define ROBOT_VEHICLE_STATUS_FRAME_ID (0x200u)
#define ROBOT_BATTERY_STATUS_FRAME_ID (0x210u)
#define ROBOT_NODE_PING_REQUEST_FRAME_ID (0x7a0u)
#define ROBOT_NODE_PING_RESP_TIVA_FRAME_ID (0x7a1u)
#define ROBOT_NODE_PING_RESP_JETSON_FRAME_ID (0x7a2u)
#define ROBOT_NODE_PING_RESP_ESP32_FRAME_ID (0x7a3u)

/* Frame lengths in bytes. */
#define ROBOT_VELOCITY_COMMAND_LENGTH (8u)
#define ROBOT_VELOCITY_FEEDBACK_LENGTH (8u)
#define ROBOT_STEERING_COMMAND_LENGTH (8u)
#define ROBOT_STEERING_FEEDBACK_LENGTH (8u)
#define ROBOT_RESET_COMMAND_LENGTH (1u)
#define ROBOT_IMU_ACCEL_LENGTH (8u)
#define ROBOT_IMU_GYRO_FLAGS_LENGTH (8u)
#define ROBOT_VEHICLE_STATUS_LENGTH (8u)
#define ROBOT_BATTERY_STATUS_LENGTH (8u)
#define ROBOT_NODE_PING_REQUEST_LENGTH (1u)
#define ROBOT_NODE_PING_RESP_TIVA_LENGTH (1u)
#define ROBOT_NODE_PING_RESP_JETSON_LENGTH (1u)
#define ROBOT_NODE_PING_RESP_ESP32_LENGTH (1u)

/* Extended or standard frame types. */
#define ROBOT_VELOCITY_COMMAND_IS_EXTENDED (0)
#define ROBOT_VELOCITY_FEEDBACK_IS_EXTENDED (0)
#define ROBOT_STEERING_COMMAND_IS_EXTENDED (0)
#define ROBOT_STEERING_FEEDBACK_IS_EXTENDED (0)
#define ROBOT_RESET_COMMAND_IS_EXTENDED (0)
#define ROBOT_IMU_ACCEL_IS_EXTENDED (0)
#define ROBOT_IMU_GYRO_FLAGS_IS_EXTENDED (0)
#define ROBOT_VEHICLE_STATUS_IS_EXTENDED (0)
#define ROBOT_BATTERY_STATUS_IS_EXTENDED (0)
#define ROBOT_NODE_PING_REQUEST_IS_EXTENDED (0)
#define ROBOT_NODE_PING_RESP_TIVA_IS_EXTENDED (0)
#define ROBOT_NODE_PING_RESP_JETSON_IS_EXTENDED (0)
#define ROBOT_NODE_PING_RESP_ESP32_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define ROBOT_STEERING_FEEDBACK_AT_TARGET_FALSE_CHOICE (0u)
#define ROBOT_STEERING_FEEDBACK_AT_TARGET_TRUE_CHOICE (1u)

#define ROBOT_STEERING_FEEDBACK_POT_FAULT_FALSE_CHOICE (0u)
#define ROBOT_STEERING_FEEDBACK_POT_FAULT_TRUE_CHOICE (1u)

#define ROBOT_STEERING_FEEDBACK_OUT_OF_RANGE_FALSE_CHOICE (0u)
#define ROBOT_STEERING_FEEDBACK_OUT_OF_RANGE_TRUE_CHOICE (1u)

#define ROBOT_STEERING_FEEDBACK_SATURATED_FALSE_CHOICE (0u)
#define ROBOT_STEERING_FEEDBACK_SATURATED_TRUE_CHOICE (1u)

#define ROBOT_RESET_COMMAND_RESET_OFF_CHOICE (0u)
#define ROBOT_RESET_COMMAND_RESET_ON_CHOICE (1u)

#define ROBOT_IMU_GYRO_FLAGS_IMU_RESET_OFF_CHOICE (0u)
#define ROBOT_IMU_GYRO_FLAGS_IMU_RESET_ON_CHOICE (1u)

#define ROBOT_VEHICLE_STATUS_GEAR_N_CHOICE (0u)
#define ROBOT_VEHICLE_STATUS_GEAR_D_CHOICE (1u)
#define ROBOT_VEHICLE_STATUS_GEAR_R_CHOICE (2u)

/* Frame Names. */
#define ROBOT_VELOCITY_COMMAND_NAME "VelocityCommand"
#define ROBOT_VELOCITY_FEEDBACK_NAME "VelocityFeedback"
#define ROBOT_STEERING_COMMAND_NAME "SteeringCommand"
#define ROBOT_STEERING_FEEDBACK_NAME "SteeringFeedback"
#define ROBOT_RESET_COMMAND_NAME "ResetCommand"
#define ROBOT_IMU_ACCEL_NAME "ImuAccel"
#define ROBOT_IMU_GYRO_FLAGS_NAME "ImuGyroFlags"
#define ROBOT_VEHICLE_STATUS_NAME "VehicleStatus"
#define ROBOT_BATTERY_STATUS_NAME "BatteryStatus"
#define ROBOT_NODE_PING_REQUEST_NAME "NodePingRequest"
#define ROBOT_NODE_PING_RESP_TIVA_NAME "NodePingRespTiva"
#define ROBOT_NODE_PING_RESP_JETSON_NAME "NodePingRespJetson"
#define ROBOT_NODE_PING_RESP_ESP32_NAME "NodePingRespEsp32"

/* Signal Names. */
#define ROBOT_VELOCITY_COMMAND_LEFT_VEL_SETPOINT_NAME "leftVelSetpoint"
#define ROBOT_VELOCITY_COMMAND_RIGHT_VEL_SETPOINT_NAME "rightVelSetpoint"
#define ROBOT_VELOCITY_FEEDBACK_LEFT_TICKS_NAME "leftTicks"
#define ROBOT_VELOCITY_FEEDBACK_RIGHT_TICKS_NAME "rightTicks"
#define ROBOT_STEERING_COMMAND_STEERING_SETPOINT_NAME "steeringSetpoint"
#define ROBOT_STEERING_FEEDBACK_STEERING_ANGLE_NAME "steeringAngle"
#define ROBOT_STEERING_FEEDBACK_AT_TARGET_NAME "at_target"
#define ROBOT_STEERING_FEEDBACK_POT_FAULT_NAME "pot_fault"
#define ROBOT_STEERING_FEEDBACK_OUT_OF_RANGE_NAME "out_of_range"
#define ROBOT_STEERING_FEEDBACK_SATURATED_NAME "saturated"
#define ROBOT_RESET_COMMAND_RESET_NAME "reset"
#define ROBOT_IMU_ACCEL_ACCEL_X_NAME "accel_x"
#define ROBOT_IMU_ACCEL_ACCEL_Y_NAME "accel_y"
#define ROBOT_IMU_ACCEL_ACCEL_Z_NAME "accel_z"
#define ROBOT_IMU_ACCEL_SEQUENCE_NAME "sequence"
#define ROBOT_IMU_ACCEL_RESERVED_NAME "reserved"
#define ROBOT_IMU_GYRO_FLAGS_GYRO_X_NAME "gyro_x"
#define ROBOT_IMU_GYRO_FLAGS_GYRO_Y_NAME "gyro_y"
#define ROBOT_IMU_GYRO_FLAGS_GYRO_Z_NAME "gyro_z"
#define ROBOT_IMU_GYRO_FLAGS_IMU_RESET_NAME "imu_reset"
#define ROBOT_IMU_GYRO_FLAGS_SEQUENCE_NAME "sequence"
#define ROBOT_VEHICLE_STATUS_SPEED_NAME "speed"
#define ROBOT_VEHICLE_STATUS_GEAR_NAME "gear"
#define ROBOT_VEHICLE_STATUS_TRIP_M_NAME "trip_m"
#define ROBOT_VEHICLE_STATUS_ODO_M_NAME "odo_m"
#define ROBOT_BATTERY_STATUS_VOLTAGE_NAME "voltage"
#define ROBOT_BATTERY_STATUS_CURRENT_NAME "current"
#define ROBOT_BATTERY_STATUS_SOC_NAME "soc"
#define ROBOT_BATTERY_STATUS_POWER_NAME "power"
#define ROBOT_BATTERY_STATUS_RANGE_NAME "range"
#define ROBOT_NODE_PING_REQUEST_SEQ_NAME "seq"
#define ROBOT_NODE_PING_RESP_TIVA_SEQ_NAME "seq"
#define ROBOT_NODE_PING_RESP_JETSON_SEQ_NAME "seq"
#define ROBOT_NODE_PING_RESP_ESP32_SEQ_NAME "seq"

/**
 * Signals in message VelocityCommand.
 *
 * Per-wheel velocity setpoints (Ackermann: 2 independent rear drives)
 *
 * All signal values are as on the CAN bus.
 */
struct robot_velocity_command_t {
    /**
     * Left rear wheel velocity setpoint
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float left_vel_setpoint;

    /**
     * Right rear wheel velocity setpoint
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float right_vel_setpoint;
};

/**
 * Signals in message VelocityFeedback.
 *
 * Cumulative signed encoder ticks per wheel (odometry source)
 *
 * All signal values are as on the CAN bus.
 */
struct robot_velocity_feedback_t {
    /**
     * Left wheel cumulative signed encoder ticks
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t left_ticks;

    /**
     * Right wheel cumulative signed encoder ticks
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int32_t right_ticks;
};

/**
 * Signals in message SteeringCommand.
 *
 * Steering angle setpoint (separate frame from velocity, per contract)
 *
 * All signal values are as on the CAN bus.
 */
struct robot_steering_command_t {
    /**
     * Steering angle setpoint (+left, REP-103)
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float steering_setpoint;
};

/**
 * Signals in message SteeringFeedback.
 *
 * Measured steering angle + status bitfield. Broadcast: consumed by BOTH JETSON and CLUSTER - the cluster reuses this frame rather than duplicating the angle into a cluster-specific frame.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_steering_feedback_t {
    /**
     * Measured steering angle from pot (+left, REP-103). Consumed by JETSON and rendered by CLUSTER.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float steering_angle;

    /**
     * b0 AT_TARGET: the CLAMPED setpoint was reached. Because it refers to the clamped value, AT_TARGET together with OUT_OF_RANGE means the request exceeded travel, was clamped, and that limit was reached - so read AT_TARGET ONLY alongside OUT_OF_RANGE.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t at_target;

    /**
     * b1 POT_FAULT: steering pot reading implausible. CLUSTER should grey out the steering display when set.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t pot_fault;

    /**
     * b2 OUT_OF_RANGE: the requested angle exceeded the mechanical travel and was clamped.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t out_of_range;

    /**
     * b3 SATURATED: the servo command hit its pulse-width limit.
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t saturated;
};

/**
 * Signals in message ResetCommand.
 *
 * Odometry reset: Tiva zeroes its encoder tick counters on receipt (Jetson sends once on activate; it does not self-zero)
 *
 * All signal values are as on the CAN bus.
 */
struct robot_reset_command_t {
    /**
     * 1 = zero the encoder tick counters now. Only bit 0 is meaningful; the whole byte is reserved so the Jetson's existing 1-byte payload maps directly. Fire-and-forget: no acknowledgement frame is sent or expected.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reset;
};

/**
 * Signals in message ImuAccel.
 *
 * IMU accelerometer X/Y/Z with sequence counter. 1 LSB = 0.001 m/s^2.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_imu_accel_t {
    /**
     * Accelerometer X (bytes 0-1)
     *
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Accelerometer Y (bytes 2-3)
     *
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Accelerometer Z (bytes 4-5)
     *
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_z;

    /**
     * Sample-cycle counter (byte 6). MUST equal ImuGyroFlags.sequence for the same sample - the Jetson rejects the whole read when they differ.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t sequence;

    /**
     * Reserved (byte 7), send 0
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved;
};

/**
 * Signals in message ImuGyroFlags.
 *
 * IMU gyroscope X/Y/Z, IMU reset flag and sequence counter. 1 LSB = 0.001 rad/s.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_imu_gyro_flags_t {
    /**
     * Gyroscope X (bytes 0-1)
     *
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Gyroscope Y (bytes 2-3)
     *
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Gyroscope Z (bytes 4-5). The TIVA pre-inverts this to the robot frame; the Jetson applies no host-side inversion.
     *
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_z;

    /**
     * 1 = the IMU was re-initialised/crashed and recovered (byte 6). The Jetson forces gyro Z to 0 and holds its existing calibration while this is set.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imu_reset;

    /**
     * Sample-cycle counter (byte 7 - NOT byte 6 as in ImuAccel). MUST equal ImuAccel.sequence for the same sample.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t sequence;
};

/**
 * Signals in message VehicleStatus.
 *
 * Instrument-cluster display status: vehicle speed + gear + trip distance (Tiva -> cluster)
 *
 * All signal values are as on the CAN bus.
 */
struct robot_vehicle_status_t {
    /**
     * Vehicle speed (converted from encoder rad/s on Tiva). Bytes 0-1, 1 LSB = 1 m/min. UNIT CHANGED 2026-08-05 from 0.1 km/h: this robot runs 0.7-2 m/s, which is 2-7 km/h (a display that looks parked) but 40-120 m/min. Whole m/min is deliberate - 1 m/min is 0.017 m/s, finer than the drive can hold, so tenths would only show noise. The signal range is the full uint16 span; the vehicle's real ceiling is far lower.
     *
     * Range: 0..65535 (0..65535 m/min)
     * Scale: 1
     * Offset: 0
     */
    uint16_t speed;

    /**
     * Gear/direction enum at BYTE 2 (moved from byte 1 when speed widened): 0=N, 1=D, 2=R, derived from encoder direction. No Park - this vehicle has no parking pawl.
     *
     * Range: 0..2 (0..2 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gear;

    /**
     * TRIP distance in metres, bytes 3-4, 1 LSB = 1 m. Accumulated on the Tiva as TOTAL PATH LENGTH (the absolute value of each increment), so reversing ADDS distance like a real trip meter rather than subtracting. RESET-RELATIVE, NOT a lifetime ODO: it zeroes on every Tiva power-cycle/reset. SATURATES at 65535 m (65.5 km) rather than wrapping. A permanent ODO needs non-volatile storage on the Tiva and is deliberately NOT this signal. See `odo_m` in bytes 5-7, which IS that signal.
     *
     * Range: 0..65535 (0..65535 m)
     * Scale: 1
     * Offset: 0
     */
    uint16_t trip_m;

    /**
     * LIFETIME odometer in metres, bytes 5-7, 1 LSB = 1 m. 24-BIT ON PURPOSE: it must outlive trip_m's uint16 (65.5 km), which a permanent odometer passes quickly. 24 bits reaches 16 777 215 m = 16 777 km - decades for this robot - and fills 0x200's last three free bytes exactly, so no new frame and no new TX slot were needed. PERSISTENT: held in the Tiva's internal EEPROM, written every 10 m of travel, and RESTORED ON BOOT - it survives resets and power cycles. It is NOT zeroed by 0x140 ResetCommand (that zeroes trip_m only), and there is no way to clear it over CAN by design. SATURATES at the signal max rather than wrapping. Worst-case loss on a sudden power-off is one write interval, i.e. 10 m.
     *
     * Range: 0..16777215 (0..16777215 m)
     * Scale: 1
     * Offset: 0
     */
    uint32_t odo_m;
};

/**
 * Signals in message BatteryStatus.
 *
 * Battery/power status for the instrument cluster (Tiva->Cluster). Tiva plays the BMS role: computes SoC (coulomb counting + voltage re-anchor), power and range from the INA226. LAYOUT AND UNITS CHANGED 2026-08-05 (v2) - every signal moved; see the byte-budget note in build_dbc.py.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_battery_status_t {
    /**
     * Bus voltage from the INA226. BYTE 0, 1 LSB = 0.1 V (NARROWED 2026-08-05 from uint16 x0.01 V to free a byte for the widened `range`). 0-25.5 V covers this 3S pack (9.0-12.6 V) with headroom. mV-precision voltage is not lost - it stays on the Tiva's UART heartbeat.
     *
     * Range: 0..255 (0..25.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t voltage;

    /**
     * Bus current from the INA226. BYTES 1-2 (MOVED from 2-3 2026-08-05), 1 LSB = 0.01 A - resolution deliberately UNCHANGED. SIGN CONVENTION: POSITIVE = DISCHARGE (current leaving the battery), NEGATIVE = CHARGE (current into the battery).
     *
     * Range: -32768..32767 (-327.68..327.67 A)
     * Scale: 0.01
     * Offset: 0
     */
    int16_t current;

    /**
     * Battery state of charge. BYTE 3 (MOVED from byte 4 2026-08-05). Computed ON THE TIVA by coulomb counting re-anchored to an IR-compensated voltage->SoC LUT at rest (3S Li-ion, 9.0-12.6 V). The cluster renders this as-is. It is an ESTIMATE - accuracy is bounded by the provisional R_source.
     *
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t soc;

    /**
     * Instantaneous power = voltage x current, computed on the Tiva. BYTES 4-5 (MOVED from 5-6), 1 LSB = 1 W. SCALE CHANGED 2026-08-05 from 0.1 kW: at 100 W/LSB this robot's entire 3-220 W range mapped to 0-2 counts, i.e. the signal was blind - confirmed on the wire in A3 step 4a, where 4.06 W transmitted as 0.0 kW. At 1 W/LSB the same range is 3-220 counts. THIS is the change that makes the POWER/REGEN strip move. Sign follows `current`: positive = discharge, negative = charge.
     *
     * Range: -32768..32767 (-32768..32767 W)
     * Scale: 1
     * Offset: 0
     */
    int16_t power;

    /**
     * Estimated remaining range, computed on the Tiva from remaining energy divided by recent consumption. BYTES 6-7, 1 LSB = 1 m (WIDENED 2026-08-05 from uint8 km - 255 km of headroom at 1 km resolution was useless on a robot whose display wants metres). CEILING: 65535 m = 65.5 km, and BATTERY_RANGE_MAX_KM was lowered from 255 to 65 to match, so a large estimate CLAMPS instead of silently wrapping to a plausible wrong number. 0 means NOT ESTIMABLE (stationary or charging), not 'empty'.
     *
     * Range: 0..65535 (0..65535 m)
     * Scale: 1
     * Offset: 0
     */
    uint16_t range;
};

/**
 * Signals in message NodePingRequest.
 *
 * Node liveness ping REQUEST, HOST -> all nodes, ~1 Hz. Every node answers on its own response id.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_node_ping_request_t {
    /**
     * Rolling request counter. Each node ECHOES THIS BYTE UNCHANGED in its own response, so the HOST can match a reply to the request that caused it and measure round-trip liveness.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t seq;
};

/**
 * Signals in message NodePingRespTiva.
 *
 * Node liveness ping RESPONSE from the TIVA. IMPLEMENTED IN THIS REPO: a dedicated RX message object matches 0x7A0 exactly (the 0x100/0x120 command filter cannot admit it), the seq is latched in the CAN dispatch with NO service involvement, and the echo is transmitted from its own super-loop slot (now%100==51) to preserve the one-Can_Transmit-per-millisecond invariant. Answered unconditionally - see the note on 0x7A0.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_node_ping_resp_tiva_t {
    /**
     * Echo of NodePingRequest.seq, byte-for-byte unchanged. No node id in the payload - the FRAME ID identifies the responder.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t seq;
};

/**
 * Signals in message NodePingRespJetson.
 *
 * Node liveness ping RESPONSE from the JETSON. NOT this repo's responsibility - defined here so the bus definition is complete.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_node_ping_resp_jetson_t {
    /**
     * Echo of NodePingRequest.seq, byte-for-byte unchanged. No node id in the payload - the FRAME ID identifies the responder.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t seq;
};

/**
 * Signals in message NodePingRespEsp32.
 *
 * Node liveness ping RESPONSE from the ESP32. NOT this repo's responsibility - defined here so the bus definition is complete.
 *
 * All signal values are as on the CAN bus.
 */
struct robot_node_ping_resp_esp32_t {
    /**
     * Echo of NodePingRequest.seq, byte-for-byte unchanged. No node id in the payload - the FRAME ID identifies the responder.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t seq;
};

/**
 * Pack message VelocityCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_velocity_command_pack(
    uint8_t *dst_p,
    const struct robot_velocity_command_t *src_p,
    size_t size);

/**
 * Unpack message VelocityCommand.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_velocity_command_unpack(
    struct robot_velocity_command_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VelocityCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_velocity_command_init(struct robot_velocity_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float robot_velocity_command_left_vel_setpoint_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_velocity_command_left_vel_setpoint_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_command_left_vel_setpoint_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_command_left_vel_setpoint_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float robot_velocity_command_right_vel_setpoint_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_velocity_command_right_vel_setpoint_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_command_right_vel_setpoint_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_command_right_vel_setpoint_is_in_phys_range(double value);

/**
 * Pack message VelocityFeedback.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_velocity_feedback_pack(
    uint8_t *dst_p,
    const struct robot_velocity_feedback_t *src_p,
    size_t size);

/**
 * Unpack message VelocityFeedback.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_velocity_feedback_unpack(
    struct robot_velocity_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VelocityFeedback.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_velocity_feedback_init(struct robot_velocity_feedback_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t robot_velocity_feedback_left_ticks_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_velocity_feedback_left_ticks_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_feedback_left_ticks_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_feedback_left_ticks_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t robot_velocity_feedback_right_ticks_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_velocity_feedback_right_ticks_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_feedback_right_ticks_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_velocity_feedback_right_ticks_is_in_phys_range(double value);

/**
 * Pack message SteeringCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_steering_command_pack(
    uint8_t *dst_p,
    const struct robot_steering_command_t *src_p,
    size_t size);

/**
 * Unpack message SteeringCommand.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_steering_command_unpack(
    struct robot_steering_command_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SteeringCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_steering_command_init(struct robot_steering_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float robot_steering_command_steering_setpoint_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_steering_command_steering_setpoint_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_command_steering_setpoint_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_command_steering_setpoint_is_in_phys_range(double value);

/**
 * Pack message SteeringFeedback.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_steering_feedback_pack(
    uint8_t *dst_p,
    const struct robot_steering_feedback_t *src_p,
    size_t size);

/**
 * Unpack message SteeringFeedback.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_steering_feedback_unpack(
    struct robot_steering_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SteeringFeedback.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_steering_feedback_init(struct robot_steering_feedback_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float robot_steering_feedback_steering_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_steering_feedback_steering_angle_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_steering_angle_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_steering_angle_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_steering_feedback_at_target_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_steering_feedback_at_target_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_at_target_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_at_target_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_steering_feedback_pot_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_steering_feedback_pot_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_pot_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_pot_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_steering_feedback_out_of_range_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_steering_feedback_out_of_range_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_out_of_range_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_out_of_range_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_steering_feedback_saturated_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_steering_feedback_saturated_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_saturated_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_steering_feedback_saturated_is_in_phys_range(double value);

/**
 * Pack message ResetCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_reset_command_pack(
    uint8_t *dst_p,
    const struct robot_reset_command_t *src_p,
    size_t size);

/**
 * Unpack message ResetCommand.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_reset_command_unpack(
    struct robot_reset_command_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ResetCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_reset_command_init(struct robot_reset_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_reset_command_reset_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_reset_command_reset_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_reset_command_reset_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_reset_command_reset_is_in_phys_range(double value);

/**
 * Pack message ImuAccel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_imu_accel_pack(
    uint8_t *dst_p,
    const struct robot_imu_accel_t *src_p,
    size_t size);

/**
 * Unpack message ImuAccel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_imu_accel_unpack(
    struct robot_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuAccel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_imu_accel_init(struct robot_imu_accel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_imu_accel_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_accel_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_accel_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_accel_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_imu_accel_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_accel_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_accel_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_accel_y_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_imu_accel_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_accel_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_accel_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_accel_z_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_imu_accel_sequence_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_accel_sequence_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_sequence_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_sequence_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_imu_accel_reserved_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_accel_reserved_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_reserved_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_accel_reserved_is_in_phys_range(double value);

/**
 * Pack message ImuGyroFlags.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_imu_gyro_flags_pack(
    uint8_t *dst_p,
    const struct robot_imu_gyro_flags_t *src_p,
    size_t size);

/**
 * Unpack message ImuGyroFlags.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_imu_gyro_flags_unpack(
    struct robot_imu_gyro_flags_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuGyroFlags.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_imu_gyro_flags_init(struct robot_imu_gyro_flags_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_imu_gyro_flags_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_gyro_flags_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_gyro_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_gyro_x_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_imu_gyro_flags_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_gyro_flags_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_gyro_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_gyro_y_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_imu_gyro_flags_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_gyro_flags_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_gyro_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_gyro_z_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_imu_gyro_flags_imu_reset_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_gyro_flags_imu_reset_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_imu_reset_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_imu_reset_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_imu_gyro_flags_sequence_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_imu_gyro_flags_sequence_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_sequence_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_imu_gyro_flags_sequence_is_in_phys_range(double value);

/**
 * Pack message VehicleStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_vehicle_status_pack(
    uint8_t *dst_p,
    const struct robot_vehicle_status_t *src_p,
    size_t size);

/**
 * Unpack message VehicleStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_vehicle_status_unpack(
    struct robot_vehicle_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VehicleStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_vehicle_status_init(struct robot_vehicle_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t robot_vehicle_status_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_vehicle_status_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_speed_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_speed_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_vehicle_status_gear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_vehicle_status_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_gear_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_gear_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t robot_vehicle_status_trip_m_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_vehicle_status_trip_m_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_trip_m_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_trip_m_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t robot_vehicle_status_odo_m_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_vehicle_status_odo_m_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_odo_m_is_in_range(uint32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_vehicle_status_odo_m_is_in_phys_range(double value);

/**
 * Pack message BatteryStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_battery_status_pack(
    uint8_t *dst_p,
    const struct robot_battery_status_t *src_p,
    size_t size);

/**
 * Unpack message BatteryStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_battery_status_unpack(
    struct robot_battery_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BatteryStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_battery_status_init(struct robot_battery_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_battery_status_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_battery_status_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_voltage_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_battery_status_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_battery_status_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_current_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_battery_status_soc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_battery_status_soc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_soc_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_soc_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t robot_battery_status_power_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_battery_status_power_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_power_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_power_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t robot_battery_status_range_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_battery_status_range_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_range_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_battery_status_range_is_in_phys_range(double value);

/**
 * Pack message NodePingRequest.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_node_ping_request_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_request_t *src_p,
    size_t size);

/**
 * Unpack message NodePingRequest.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_node_ping_request_unpack(
    struct robot_node_ping_request_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NodePingRequest.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_node_ping_request_init(struct robot_node_ping_request_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_node_ping_request_seq_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_node_ping_request_seq_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_request_seq_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_request_seq_is_in_phys_range(double value);

/**
 * Pack message NodePingRespTiva.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_node_ping_resp_tiva_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_resp_tiva_t *src_p,
    size_t size);

/**
 * Unpack message NodePingRespTiva.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_node_ping_resp_tiva_unpack(
    struct robot_node_ping_resp_tiva_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NodePingRespTiva.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_node_ping_resp_tiva_init(struct robot_node_ping_resp_tiva_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_node_ping_resp_tiva_seq_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_node_ping_resp_tiva_seq_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_resp_tiva_seq_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_resp_tiva_seq_is_in_phys_range(double value);

/**
 * Pack message NodePingRespJetson.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_node_ping_resp_jetson_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_resp_jetson_t *src_p,
    size_t size);

/**
 * Unpack message NodePingRespJetson.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_node_ping_resp_jetson_unpack(
    struct robot_node_ping_resp_jetson_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NodePingRespJetson.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_node_ping_resp_jetson_init(struct robot_node_ping_resp_jetson_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_node_ping_resp_jetson_seq_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_node_ping_resp_jetson_seq_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_resp_jetson_seq_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_resp_jetson_seq_is_in_phys_range(double value);

/**
 * Pack message NodePingRespEsp32.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int robot_node_ping_resp_esp32_pack(
    uint8_t *dst_p,
    const struct robot_node_ping_resp_esp32_t *src_p,
    size_t size);

/**
 * Unpack message NodePingRespEsp32.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int robot_node_ping_resp_esp32_unpack(
    struct robot_node_ping_resp_esp32_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from NodePingRespEsp32.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int robot_node_ping_resp_esp32_init(struct robot_node_ping_resp_esp32_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t robot_node_ping_resp_esp32_seq_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double robot_node_ping_resp_esp32_seq_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_resp_esp32_seq_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool robot_node_ping_resp_esp32_seq_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
