/******************************************************************************
 *
 * Module: TimerPWM (MCAL)
 *
 * File Name: timer_pwm.h
 *
 * Description: Public API for the generic WTIMER0 Timer-PWM driver.
 *
 *  A neutral, pulse-domain PWM output primitive: 50Hz frame, pulse width set
 *  in microseconds. Generated by WTIMER0 TimerA in PWM mode on WT0CCP0 = PC4.
 *  Independent of the PWM0 motor peripheral and of the shared RCC PWMDIV.
 *
 *  This is the MCAL: it knows ONLY about timers and microseconds. It has no
 *  concept of "servo", "angle" or "center" - those belong to the Servo HAL
 *  (servo.h), which calls this driver, mirroring how Motor.c calls PWM.c.
 *
 ******************************************************************************/

#ifndef TIMER_PWM_H_
#define TIMER_PWM_H_

#include "Platform_Types.h"
#include "timer_pwm_cfg.h"

/*******************************************************************************
 *                          Type Definitions                                   *
 *******************************************************************************/

typedef enum {
    TIMER_PWM_OK = 0,
    TIMER_PWM_ERROR_NOT_INITIALIZED
} TimerPWM_StatusType;

/*******************************************************************************
 *                          Function Prototypes                                *
 *******************************************************************************/

/**
 * @brief  One-time bring-up of WTIMER0/TimerA as a 50Hz PWM generator.
 *         Enables the WTIMER0 clock, waits for ready, configures TimerA for
 *         50Hz down-counting PWM (split 32-bit, periodic+PWM, non-inverted,
 *         TAILR=319999), loads the neutral midpoint pulse
 *         (TIMER_PWM_INIT_PULSE_US), and starts the output.
 * @note   The WT0CCP0 pin (PC4) must already be muxed by the PORT driver.
 *         Call ONCE at boot, after Port_Init(). Typically invoked by
 *         Servo_Init() rather than directly.
 */
void TimerPWM_Init(void);

/**
 * @brief  Set the PWM pulse width in microseconds (the actuation primitive).
 * @param  pulse_us: target pulse width. Values outside
 *         [TIMER_PWM_MIN_PULSE_US, TIMER_PWM_MAX_PULSE_US] are CLAMPED into
 *         range rather than rejected (matches the PWM driver's clamp policy).
 * @return TIMER_PWM_OK, or TIMER_PWM_ERROR_NOT_INITIALIZED if called before
 *         TimerPWM_Init().
 */
TimerPWM_StatusType TimerPWM_SetPulseUs(uint16 pulse_us);

/**
 * @brief  Stop the PWM output by disabling TimerA (clears GPTMCTL.TAEN). The
 *         CCP pin stops toggling (no pulse). This is the primitive the HAL's
 *         Servo_Disable() builds on. Re-enable by calling TimerPWM_Init()
 *         (or, future, a dedicated re-enable) - SetPulseUs alone does not
 *         restart a stopped timer.
 */
void TimerPWM_Stop(void);

#endif /* TIMER_PWM_H_ */
